"""Unit and pixel constants shared across the package."""

from __future__ import annotations

__all__ = [
    "BYTES_PER_KB",
    "BYTES_PER_MB",
    "COLOR_SAMPLE_SIZE",
    "MAX_BASE64_LENGTH",
    "MAX_BLURHASH_COMPONENTS",
    "MAX_BUNDLE_PALETTE_N",
    "MAX_CHANNEL_VALUE",
    "MAX_DIRECTORY_SCAN",
    "MAX_DUPLICATE_SCAN",
    "MAX_FAVICON_SIZES",
    "MAX_GIF_FRAMES",
    "MAX_GIF_TOTAL_PIXELS",
    "MAX_HASH_SIZE",
    "MAX_HTML_BASE64_BYTES",
    "MAX_IMAGE_DIMENSION",
    "MAX_INPUT_BYTES",
    "MAX_NEAR_DUPLICATE_SCAN",
    "MAX_PDF_DPI",
    "MAX_PDF_IMAGES",
    "MAX_PDF_PAGES",
    "MAX_PDF_SIZE_BYTES",
    "MAX_PDF_TOTAL_PIXELS",
    "MAX_PRESET_FILE_SIZE_BYTES",
    "MAX_QUALITY",
    "MAX_SCAN_ENTRIES",
    "MAX_SSIM_PIXELS",
    "MAX_SPRITE_IMAGES",
    "MAX_SPRITE_TOTAL_PIXELS",
    "MAX_SRCSET_WIDTHS",
    "MAX_UNIQUE_COLORS",
    "MIN_QUALITY",
    "PERCENT",
    "SMART_FORMAT_PHOTO_THRESHOLD",
    "WHITE",
]

# Byte unit conversion
BYTES_PER_KB = 1024
BYTES_PER_MB = 1024 * 1024

# Max value for an 8-bit channel
MAX_CHANNEL_VALUE = 255

# Common colors
WHITE: tuple[int, int, int] = (MAX_CHANNEL_VALUE, MAX_CHANNEL_VALUE, MAX_CHANNEL_VALUE)

# Quality / percentage
MIN_QUALITY = 1
MAX_QUALITY = 100
PERCENT = 100

# Smart format detection
COLOR_SAMPLE_SIZE = 100
MAX_UNIQUE_COLORS = 1024
SMART_FORMAT_PHOTO_THRESHOLD = 300

# Security / resource limits
MAX_INPUT_BYTES = 100 * 1024 * 1024  # 100 MB
MAX_BASE64_LENGTH = 1024 * 1024  # 1 MB
MAX_PRESET_FILE_SIZE_BYTES = 1024 * 1024  # 1 MB
MAX_PDF_SIZE_BYTES = 50 * 1024 * 1024  # 50 MB
MAX_PDF_PAGES = 100
MAX_PDF_DPI = 2400
MAX_IMAGE_DIMENSION = 30000
MAX_SRCSET_WIDTHS = 20
MAX_HASH_SIZE = 64
MAX_BLURHASH_COMPONENTS = 9
MAX_BUNDLE_PALETTE_N = 32
MAX_DUPLICATE_SCAN = 10000

# Resource limits to avoid unbounded memory usage
MAX_GIF_FRAMES = 200
MAX_GIF_TOTAL_PIXELS = 1_000_000_000  # 1 billion pixels (~4 GB at RGBA)
MAX_SPRITE_IMAGES = 200
MAX_FAVICON_SIZES = 20
MAX_HTML_BASE64_BYTES = 10 * 1024 * 1024  # 10 MB

# Additional resource budgets to prevent CPU/memory exhaustion
MAX_SSIM_PIXELS = 4_000_000  # 4 megapixels
MAX_NEAR_DUPLICATE_SCAN = 1_000
MAX_SPRITE_TOTAL_PIXELS = 1_000_000_000  # 1 billion source pixels
MAX_PDF_IMAGES = 100
MAX_PDF_TOTAL_PIXELS = 1_000_000_000  # 1 billion total pixels
MAX_SCAN_ENTRIES = 10_000
MAX_DIRECTORY_SCAN = 10_000
